### ISSUE TITLE
Azure web+sql kérdés

### ISSUE THREAD

**Issue by WillieV4S** [cloudsteak/mentor-klub-azure#1]
Kedves Tibor!
A trn-azure-webapp-sql repository-ban leírtak szerint próbáltam létrehozni az sql adatbázist. Sajnos annál a résznél, ahol az Azure AD rendszergazda beállításánál ki kell válasszuk a felhasználónkat, nálam nem jelenik meg sajnos semmi. Ez azért lehet, mert bizonyos funkciók le vannak tiltva a mentorklub2023 erőforráscsoportban vagy én rontok el valamit? Esetleg csak saját előfizetésben működik számomra ez a funkció? Előre is köszönöm a szíves választ!
Üdvözlettel:
Vilmos

**Comment by the1bit** [comment]
Szia,

Ne haragudj a kései válaszért.

Ha nem jelenik meg semmi, akkor sincs baj. 
Ugyanis a `SQL-hitelesítés használata` is elegendő számunkra. Tehát válaszd azt. a lehetőséget.
<img width="692" alt="image" src="https://github.com/cloudsteak/mentor-klub-azure/assets/32801432/64b8366a-7012-4944-9577-5b29f6382107">

Ez esetben távolról az alkalmazás és Te is a `Kiszolgáló rendszergazdájának felhasználóneve` részben megadott technikai felhasználóval tudsz bejelentkezni az adatbázisba.

Megjegyzés: Ha szeretnél a saját számítógépedről csatlakozni az adatbázishoz, akkor az adatbázisnál, a tűzfal beállításoknál, el ne felejtsd hozzáadni a saját géped nyilvános IP címét. :-)

Remélem ez megoldja a problémád. :-)

**Comment by WillieV4S** [comment]
Szia Tibor!
Köszönöm szépen a választ!
Sikerült megoldani! :-)
Üdv.:
Vilmos
