### ISSUE TITLE
Pipeline issue

### ISSUE THREAD

**Issue by TennisKiller95** [cloudsteak/mentor-klub-azure#10]
Szia Tibi!

Eljutottam a Dockeres videóban addig, hogy a Container Registryvel létrehozzuk a Pipelinet.
Ugye el is mondod, hogy magasabb jogosultság kell a létrehozoásához.
Hogyan tudom létrehozni?
Azure DEVOPS-ban nem jelenik meg a Docker registrys kapcsolat a Service Connectionsnél
Előre is köszönöm a segítségedet

Üdv. Gábor

**Comment by the1bit** [comment]
Szia,

A videóban az hangzik el, hogy magasabb jogosultság kell, ami nektek nincs. Ez így is van, mert tulajdonosi jogkör kell hozzá. Ezért van minden beállítva előre Azure DevOps-ban. 🙂

A kapcsolat (ARCKAPCSOLAT) ott van és működik. Használtad is.

Tudnál küldeni egy képernyőképet, hogy mit látsz?
Úgy érzem, valami nálad másképpen történik,mint kellene. 

Köszönöm
