### ISSUE TITLE
Azure trn-node-docker-demo

### ISSUE THREAD

**Issue by WillieV4S** [cloudsteak/mentor-klub-azure#3]
### Miben segíthetek?

Kedves Tibor!
Azure DevOps-ban szeretnék új service connection-t létrehozni Docker Registry-hez. A Registry tipusnál kiválasztom az ACR-t, Authentication tipusnál kiválasztom a Service Principal-t, Subscription-nél az Azure Képzést, az Azure container registry-nél a mentorklubacr-t, megadok egy nevet a Service connection name-nél, de nem engedi bepipálni a "Grant access permission to all pipelines" részt, illetve a következő hibaüzenetet kapom, ha létre akarom hozni a kapcsolatot:
Failed to create an app in Azure Active Directory. Error: Insufficient privileges to complete the operation in Microsoft Graph Ensure that the user has permissions to create an Azure Active Directory Application.
Szeretném a szíves segítségedet kérni!
Köszönöm!
Vilmos

### Témakör

Azure

**Comment by the1bit** [comment]
Kedves @WillieV4S ,

Teljesen jó az észrevétel és örülök, hogy eddig eljutottál. :-)

Az `Azure Képzés` előfizetéshez nem is lesz jogod, mivel oda `tulajdonos` vagy `társ tulajdonos` jogosultság szükséges.
Ilyen szempontból vannak korlátai ennek a fajta hozzáférésnek ,amit Ti kaptok.

Kérlek próbáld meg most, hogy a `mentorklubacr` kapcsolatot használod. Módosítottam kicsit a jogosultságokat. :-)

Azt szoktam javasolni, hogy a saját Azure előfizetésben legyen létrehozva a az egész. :-)


T.

**Comment by the1bit** [comment]
@WillieV4S Látom megoldódott. :-)

Örülök.

**Comment by WillieV4S** [comment]
Kedves Tibor!
Elnézést, hogy csak most válaszolok, de próbáltam gyorsan megcsinálni,
mielőtt elmegyek a gyerekekért az iskolába, óvódába...
Nagyon köszönöm a segítséget, így jobb, ha az ember teljesen végig tudja
csinálni a feladatot. :-) Próbálok minden gyakorlatot minél többször
megcsinálni még év végéig, amíg nem törlöd a felhasználókat. Nagyon
megtetszett ez az egész Azure téma, amiket bemutattál! :-) Ez nagyban
köszönhető annak, hogy mindent tök jól elmagyaráztál, nagyon jók és
látványosak a demók. :-) Szívesen foglalkozok ilyenekkel. Várom az AWS-ből
is az újabb és bővebb oktatóanyagot.
Remélem hamarosan ahhoz is szerencsénk lesz! :-)
Esetleg, ha nagyon sok feladatod lenne és van olyan, amiben tudok segíteni,
akkor mindenféleképpen jelezd, légyszíves. Szívesen vállalnám!
Természetesen a gyakorlat szerzés lenne a célom, semmi más.
Sajnos kevés ilyen ember van, aki ennyire szívesen adja át a tudást mint te
és nagyon örülök, hogy részt tudtam venni ezekben a kurzusokban!
Üdvözlettel:
Vilmos

Tibor Kiss ***@***.***> ezt írta (időpont: 2023. nov. 28., K,
16:11):
