### ISSUE TITLE
Azure hozzáférés engedélyezve - Több hetes képzés[Q]: 

### ISSUE THREAD

**Issue by LiberP12** [cloudsteak/mentor-klub-azure#6]
### Miben segíthetek?

Kedves Tibor!
Nem tudom aktiválni a cloudsteak.com-os címtárat a Microsoft Azureban.
Mellékelve csatolom a lépéseket amiket végrehajtottam.
[cloudsteak.docx](https://github.com/cloudsteak/mentor-klub-azure/files/14462747/cloudsteak.docx)

### Témakör

Azure

**Comment by the1bit** [comment]
Szia,

Köszönöm, hogy írtál. Megnézem részletesen és írok.

**Comment by LiberP12** [comment]
Szerintem az lehet a probléma, hogy github-os fiókkal regisztráltam az Azure-ban és valamiért nem tud úgy szinkronizálni, bár látszólag minden rendben és tudom használni az Azure-os fiókot.
Korábban próbáltam egy másik fiókkal (libercloud@outlook.hu) is engedélyt kérni, de arra meg azt írta (https://mentor-access-manager.azurewebsites.net/), hogy nem érvényes email cím.  
A mostani engedélykérésem(2024.03.02.) már kiment a libercloud@outlook.hu-s email címről.

**Comment by the1bit** [comment]
Mindegyik kérés beérkezett és jóvá is hagytam. 😃 

Nem a GitHub lesz a probléma, hanem hogy már a bejelentkezett "session"-el próbálsz bejelentkezni, aminek habár ugyanaz az email címe, mégis egy teljesen más típusú felhasználó.
Azure esetén ugyanazzal az email címmel ugyanis két féle fiókot is létre lehet hozni.
- Personal
- Work and school

És itt össze tud keveredni a dolog.

Azt tedd már meg hogy teljesen kijelentkezel az eredeti account-al, ha lehet felejtse is el azt a böngésződ, majd utána jelentkezz be újra cloudsteak.com tarományba.

És annak a felhasználónak, ne a másik előfizetéshez tartozó jelszavát használd. 😃

**Comment by LiberP12** [comment]
Köszönöm a segítséget, a libercloud-os címmel most elsőre sikerült belépnem és látom a cloudsteak-es címtárat. :)
