### ISSUE TITLE
szula 

### ISSUE THREAD

**Issue by szuhalaci** [cloudsteak/mentor-klub-azure#7]
### Miben segíthetek?

Szia,
Kértem hozzáférést a Mentor Klubból, még nem kaptam meg. Spamot is néztem. szuha.laszlo@gmail.com címmel kértem Szuha László névvel. Köszi.

### Témakör

Általános kérdés

**Comment by the1bit** [comment]
Szia,


Nem látok ilyen igényt. 
El tudnád újra küldeni?


Köszi

**Comment by szuhalaci** [comment]
Elment ismét,

Köszi

**Comment by the1bit** [comment]
Helytelenül adtad meg a biztonsági szót. 

A helyes biztonsági szó a képzés oldalán található.

:-)

**Comment by the1bit** [comment]
Sikerül az igénylés

**Comment by szuhalaci** [comment]
Bocsi, arra nem is figyeltem
