### ISSUE TITLE
Workflow jóváhagyása

### ISSUE THREAD

**Issue by TennisKiller95** [cloudsteak/mentor-klub-azure#8]
Tisztelt Tibor!

Az Azure haladó képzés 5. videója kapcsán elkezdtem forkolni a repositorydat.
Viszont ugye nem futnak le a CI/CD folyamatok, mivel a jóváhagyásodra lenne szükség.
Jóváhagynád kérlek a következő repositoryban lévő workflowkat?
Köszönöm előre is
Itt a link: https://github.com/TennisKiller95/trn-node-demo

Üdv. Gábor

**Comment by the1bit** [comment]
Szia,

A videóban említettem, hogy ne az eredeti respository-ba (https://github.com/cloudsteak/trn-node-demo) indítsátok a Pull Request-et, hanem a sajátotokba. (https://github.com/TennisKiller95/trn-node-demo)
Itt a példa: https://github.com/cloudsteak/trn-node-demo/issues/102#issuecomment-2470575620

A Pull Request-eket le is zártam emiatt.

A jövőben, kérlek itt írj, ha valami elakadásod van: https://github.com/cloudsteak/mentor-klub-cloud/issues/new/choose

Köszi,
Tibi

**Comment by TennisKiller95** [comment]
Szia Tibi!

Köszönöm szépen, akkor ez alapján elfogok tudni szerintem indulni.

Üdv. Gábor

Tibor Kiss ***@***.***> ezt írta (időpont: 2024. dec. 3., K,
13:03):

**Comment by the1bit** [comment]
Örülök és szívesen. : -)
