### ISSUE TITLE
[Q]: trn-doacker project

### ISSUE THREAD

**Issue by TennisKiller95** [cloudsteak/mentor-klub-azure#9]
### Miben segíthetek?

Szia Tibi!

Ismét problémába ütköztem, méghozzá a hatodik dockeres videó kapcsán.
Ugye feltelepítettem a Docker desktopot, viszont az alábbi hibaüzenet jelenik meg amikor a VS Codeban probálnám létrehozni az Imaget: bash: docker: command not found
Hogyan tudom ezen problémát orvosolni?
Válaszodat előre is köszönöm.

Üdv. Gábor

### Témakör

Általános kérdés

**Comment by the1bit** [comment]
Szia,

Valószínűleg a VS Code nyitva volt, amikor a Docker Desktop-ot telepítetted, így még a docker parancs elérési útja nem volt benne a PATH-ban.

Indítsd újra a VS Code-ot (minden példányt). Ha nem segít, akkor az egész gépet.

Üdv:
Tibi

**Comment by TennisKiller95** [comment]
Szia Tibi!

Köszönöm szèpen

Üdv. Gábor

Tibor Kiss ***@***.***> ezt írta (időpont: 2024. dec. 6., P
17:39):
